name: Multigol

on:
workflow_dispatch:

jobs:
build:
runs-on: ubuntu-latest


steps:
  - name: Checkout
    uses: actions/checkout@v3

  - name: Setup Python
    uses: actions/setup-python@v4
    with:
      python-version: "3.10"

  - name: Install requirements
    run: pip install -r requirements.txt

  - name: Get matches
    run: python get_matches.py

  - name: Get odds
    run: python odds_api_scraper.py

  - name: Run engine
    run: python multigol_engine.py

